[[redirects]]
  from = "dashboard/selected-course/*"
  to = "https://thingproxy.freeboard.io/fetch//:splat"
  status = 200

  [[redirects]]
  from = "/selected-course"
  to = "https://thingproxy.freeboard.io/fetch//:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"